### ISSUE TITLE
adding Code-of-Conduct file

### ISSUE THREAD

**Issue by goodchai0** [fdebrain/stock-screening-dashboard#4]
This will help contributor to know the rules and regulation for contributing.
Please assign this to me under hacktoberfest 2022. @fdebrain

**Comment by fdebrain** [comment]
Hi @goodchai0 and thanks for the suggestion! I just assigned you

**Comment by goodchai0** [comment]
can you add "hacktoberfest-accepted" label too, otherwise the PR wont be counted.

**Comment by fdebrain** [comment]
> can you add "hacktoberfest-accepted" label too, otherwise the PR wont be counted.

Done! Don't forget to :star: the project :)

**Comment by goodchai0** [comment]
sure. done
